name: Close Stale Issues

on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 0
          days-before-issue-close: 0
          ignore-issue-updates: true
          close-issue-message: "Dear friend, this issue has been stale for too long and must be closed. Many thanks!"
          close-issue-reason: not_planned
