name: Dependent Jobs

on:
  workflow_dispatch:

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am job 1"
  j2:
    runs-on: ubuntu-latest
    needs: j1
    steps:
      - run: exit 1
      
  j3:
    runs-on: ubuntu-latest
    needs: j2
    steps:
      - run: echo "I can't run!"
      
  j4:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [j1, j2, j3]
    steps:
      - run: echo "Can I run?"
