name: Issue workflow command


on:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Set Notice Message
        run: echo "::notice::This is a notice message"
      - name: Set file notice message
        run: echo "::warning file=README.md,line=2,col=5,endColumn=7,title=ERROR::Readme has problem"
