name: Issue workflow command


on:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Set Notice Message
        run: echo "::notice::This is a notice message"
      - name: Set file notice message
        run: echo "::warning file=index.js,line=2,col=5,endColumn=7,title=ERROR::index has problem"
      - name: Mask simple string
        run: echo "Your password is"; echo "::add-mask::sonic1"
      - name: Job Summary
        run: echo "# 💣" >> $GITHUB_STEP_SUMMARY
